import {
  IconAlertCircleFilled,
  IconAlertTriangle,
  IconArrowRight,
  IconBold,
  IconBrandGoogle,
  IconCategory,
  IconCategory2,
  IconCheck,
  IconCheckbox,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconClock,
  IconCode,
  IconDashboard,
  IconDeviceLaptop,
  IconDotsVertical,
  IconEdit,
  IconEye,
  IconFilter,
  IconGridPattern,
  IconH1,
  IconH2,
  IconH3,
  IconHome,
  IconItalic,
  IconLeaf,
  IconList,
  IconListNumbers,
  IconLoader,
  IconLogout2,
  IconMail,
  IconMapPin2,
  IconMedal,
  IconMenu2,
  IconMessagePlus,
  IconMoon,
  IconMountain,
  IconNews,
  IconPackage,
  IconPhone,
  IconPhoto,
  IconPhotoFilled,
  IconPhotoPlus,
  IconPlant,
  IconPlus,
  IconQuote,
  IconReportAnalytics,
  IconSearch,
  IconSend2,
  IconSettings,
  IconShieldBolt,
  IconStrikethrough,
  IconSun,
  IconTrash,
  IconTrashXFilled,
  IconTypography,
  IconUnderline,
  IconUser,
  IconUsersGroup,
  IconX,
  TablerIcon,
} from "@tabler/icons-react";

export type Icon = TablerIcon;

export const Icons = {
  add: IconPlus,
  edit: IconEdit,
  loader: IconLoader,
  moreVertical: IconDotsVertical,
  check: IconCheck,
  close: IconX,
  filter: IconFilter,
  checkSquare: IconCheckbox,
  code: IconCode,
  chevronDown: IconChevronDown,
  bold: IconBold,
  italic: IconItalic,
  underline: IconUnderline,
  strike: IconStrikethrough,

  h1: IconH1,
  h2: IconH2,
  h3: IconH3,
  list: IconList,
  numberList: IconListNumbers,
  messagePlus: IconMessagePlus,
  text: IconTypography,
  quote: IconQuote,
  danger: IconAlertCircleFilled,
  sun: IconSun,
  moon: IconMoon,
  laptop: IconDeviceLaptop,
  menu: IconMenu2,
  google: IconBrandGoogle,
  mapPin: IconMapPin2,
  mail: IconMail,
  clock: IconClock,
  phone: IconPhone,
  send: IconSend2,
  delete: IconTrashXFilled,
  addImage: IconPhotoPlus,
  plus: IconPlus,
  product: IconPackage,
  productCategory: IconCategory,
  newsCategory: IconCategory2,
  productSubCategory: IconGridPattern,
  arrowRight: IconArrowRight,
  users: IconUsersGroup,
  leaf: IconLeaf,
  eye: IconEye,
  medal: IconMedal,
  user: IconUser,
  settings: IconSettings,
  logout: IconLogout2,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  plant: IconPlant,
  mountain: IconMountain,
  search: IconSearch,
  shield: IconShieldBolt,
  dashboard: IconDashboard,
  chart: IconReportAnalytics,
  media: IconPhoto,
  mediaFilled: IconPhotoFilled,
  news: IconNews,
};
